; 请勿直接编辑本文件，以下内容由核心加载器自动生成。雪星/(20210318)
global CapsLockX_模块路径 := "./Modules"
global CapsLockX_核心路径 := "./Core"
global CapsLockX_Version := "1.27.0"
global CapsLockX_VersionName := "v1.27.0"

GoSub CapsLockX_ModuleSetup_1
GoSub CapsLockX_ModuleSetup_2
GoSub CapsLockX_ModuleSetup_3
GoSub CapsLockX_ModuleSetup_4
GoSub CapsLockX_ModuleSetup_5
GoSub CapsLockX_ModuleSetup_6
GoSub CapsLockX_ModuleSetup_7
GoSub CapsLockX_ModuleSetup_8
GoSub CapsLockX_ModuleSetup_9
GoSub CapsLockX_ModuleSetup_10
GoSub CapsLockX_ModuleSetup_11
GoSub CapsLockX_ModuleSetup_12
GoSub CapsLockX_ModuleSetup_13
GoSub CapsLockX_ModuleSetup_14
GoSub CapsLockX_ModuleSetup_15
GoSub CapsLockX_ModuleSetup_16
GoSub CapsLockX_ModuleSetup_18
GoSub CapsLockX_ModuleSetup_19
GoSub CapsLockX_ModuleSetup_20
GoSub CapsLockX_ModuleSetup_21
GoSub CapsLockX_ModuleSetup_22
GoSub CapsLockX_ModuleSetup_23
GoSub CapsLockX_ModuleSetup_24
GoSub CapsLockX_ModuleSetup_25
GoSub CapsLockX_ModuleSetup_26
GoSub CapsLockX_ModuleSetup_27
GoSub CapsLockX_ModuleSetup_28
GoSub CapsLockX_ModuleSetup_29
GoSub CapsLockX_ModuleSetup_30
GoSub CapsLockX_ModuleSetup_31
GoSub CapsLockX_ModuleSetup_32
GoSub CapsLockX_ModuleSetup_33
GoSub CapsLockX_ModuleSetup_34
GoSub CapsLockX_ModuleSetup_35
GoSub CapsLockX_ModuleSetup_36
